plugins {
    id 'java'
    id 'application'
}

group = 'com.amrts'
version = '3.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

application {
    mainClass = 'com.amrts.fridahelper.cli.FridaHelperCli'
}

jar {
    manifest {
        attributes 'Main-Class': 'com.amrts.fridahelper.cli.FridaHelperCli'
    }
}

test {
    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "full"
    }
}
