// Root build file for FridaHelper multi-module project.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

allprojects {
    group = 'com.amrts'
    version = '3.3.0'
}

subprojects {
    repositories {
        google()
        mavenCentral()
    }
}
